sudo: required

language: python

services:
  - docker

before_install:
  - git clone https://github.com/cvxgrp/cvxpy.git $HOME/cvxpy
  - docker pull cvxgrp/cvxcanon

script:
  - docker run -v $TRAVIS_BUILD_DIR:/build/CVXcanon -v $HOME/cvxpy:/build/cvxpy cvxgrp/cvxcanon /build/CVXcanon/tools/run_ci.sh

notifications:
  email: false
